language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - PHPUNIT_ARGS=--group=no-deps
  - COMPOSER_PACKAGES=silex/silex:~1.0 PHPUNIT_ARGS=--group=deps-silex
  - COMPOSER_PACKAGES="symfony/config:~2.0 symfony/dependency-injection:~2.0" PHPUNIT_ARGS=--group=deps-kernel
  - COMPOSER_PACKAGES=laravel/laravel:~4.1 PHPUNIT_ARGS=--group=deps-laravel
  - COMPOSER_PACKAGES=silex/silex:~2.0@dev PHPUNIT_ARGS=--group=deps-silex

before_install:
  - composer self-update

install:
  - composer install --dev --prefer-source
  - composer require ${COMPOSER_PACKAGES}
  - composer require satooshi/php-coveralls:dev-master

script:
  - phpunit -v --coverage-text --coverage-clover ./build/logs/clover.xml ${PHPUNIT_ARGS}

after_script:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
