language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SILEX_VERSION=~1.0@dev
  - SILEX_VERSION=~2.0@dev

before_install:
  - composer self-update

install:
  - composer install --dev --prefer-source
  - composer remove --dev --update-with-dependencies silex/silex
  - composer require silex/silex:${SILEX_VERSION}
  - composer require satooshi/php-coveralls:dev-master

script:
  - phpunit -v --coverage-text --coverage-clover ./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
