language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update

install:
  - composer install --prefer-source
  - composer require satooshi/php-coveralls:dev-master

script:
  - phpunit -v --coverage-text --coverage-clover ./build/logs/clover.xml

after_script:
  - if [ "`php -m | grep -i xdebug`" ]; then php vendor/bin/coveralls -v; fi

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
