language: php

dist: trusty
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

matrix:
  include:
    - php: 5.6
      env: dependencies=lowest
    - php: 7.1
      env: dependencies=highest
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache/files

install:
  - if [ -z "$dependencies" ]; then travis_retry composer install --no-interaction; fi;
  - if [ "$dependencies" = "lowest" ]; then travis_retry composer update --prefer-lowest --no-interaction; fi;
  - if [ "$dependencies" = "highest" ]; then travis_retry composer update --no-interaction; fi;
  - composer show

script:
  - vendor/bin/phpunit -v --coverage-text --coverage-clover=./build/logs/clover.xml

after_success:
  - if [ -f ./build/logs/clover.xml ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then travis_retry composer require satooshi/php-coveralls --no-interaction --update-with-dependencies; fi
  - if [ -f ./build/logs/clover.xml ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi
  - if [ -f ./build/logs/clover.xml ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ -f ./build/logs/clover.xml ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml; fi
